name: CI

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/ci.yml
      - src/**
  pull_request:
    branches:
      - main

  # add manual trigger
  workflow_dispatch:

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      # run tests
      - run: yarn install
      - run: yarn lint
